// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AbsenceManagerDbContext))]
    [Migration("20260331094238_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-1",
                            CreatedAt = new DateTime(2026, 3, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            DisplayName = "András Bátori",
                            Email = "batori@email.com",
                            EntraObjectId = "entra-1",
                            IsActive = true,
                            JobTitle = "Software Engineer",
                            TenantId = "tenant-1"
                        },
                        new
                        {
                            Id = "user-2",
                            CreatedAt = new DateTime(2026, 3, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            DisplayName = "Fenyvesi Barnabás",
                            Email = "fenyvesi@email.com",
                            EntraObjectId = "entra-2",
                            IsActive = true,
                            JobTitle = "GYAKORNOK",
                            TenantId = "tenant-1"
                        });
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "loc-budapest",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Budapest HQ"
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Name")
                        .IsUnique();

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "office-bp-1",
                            Description = "Main open office area",
                            DisplayOrder = 1,
                            IsActive = true,
                            LocationId = "loc-budapest",
                            Name = "Open Office - 1st Floor"
                        },
                        new
                        {
                            Id = "office-bp-2",
                            Description = "Silent workspace",
                            DisplayOrder = 2,
                            IsActive = true,
                            LocationId = "loc-budapest",
                            Name = "Quiet Room"
                        });
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkstationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_AppUser_BookingDate_IsCancelled");

                    b.HasIndex("WorkstationId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_Workstation_BookingDate_IsCancelled");

                    b.ToTable("OfficeBookings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "booking-1",
                            BookingDate = new DateOnly(2026, 3, 30),
                            CreatedAtUtc = new DateTime(2026, 3, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "user-1",
                            IsCancelled = false,
                            UserId = "user-1",
                            WorkstationId = "ws-1"
                        },
                        new
                        {
                            Id = "booking-2",
                            BookingDate = new DateOnly(2026, 3, 30),
                            CreatedAtUtc = new DateTime(2026, 3, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "user-2",
                            IsCancelled = false,
                            UserId = "user-2",
                            WorkstationId = "ws-2"
                        });
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OfficeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId", "Code")
                        .IsUnique();

                    b.HasIndex("OfficeId", "Name")
                        .IsUnique();

                    b.ToTable("Workstations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ws-1",
                            Code = "A1",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Desk A1",
                            OfficeId = "office-bp-1",
                            PositionX = 1m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-2",
                            Code = "A2",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Desk A2",
                            OfficeId = "office-bp-1",
                            PositionX = 2m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-3",
                            Code = "A3",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Desk A3",
                            OfficeId = "office-bp-1",
                            PositionX = 3m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-4",
                            Code = "Q1",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Quiet Desk 1",
                            OfficeId = "office-bp-2",
                            PositionX = 1m,
                            PositionY = 1m
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany("Offices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.HasOne("Entities.Models.AppUser", "User")
                        .WithMany("OfficeBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Workstation", "Workstation")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.HasOne("Entities.Models.Office", "Office")
                        .WithMany("Workstations")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Navigation("OfficeBookings");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
