// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AbsenceManagerDbContext))]
    [Migration("20260417114046_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "loc-Fót",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Fót"
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Name")
                        .IsUnique();

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "office-ft-1",
                            Description = "IT fejlesztés",
                            DisplayOrder = 1,
                            IsActive = true,
                            LocationId = "loc-Fót",
                            Name = "113 - IT Office"
                        });
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkstationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_AppUser_BookingDate_IsCancelled");

                    b.HasIndex("WorkstationId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_Workstation_BookingDate_IsCancelled");

                    b.ToTable("OfficeBookings", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OfficeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId", "Code")
                        .IsUnique();

                    b.HasIndex("OfficeId", "Name")
                        .IsUnique();

                    b.ToTable("Workstations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ws-1",
                            Code = "KL",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "1",
                            OfficeId = "office-ft-1",
                            PositionX = 1m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-2",
                            Code = "GV",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "2",
                            OfficeId = "office-ft-1",
                            PositionX = 2m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-3",
                            Code = "KI",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "3",
                            OfficeId = "office-ft-1",
                            PositionX = 3m,
                            PositionY = 1m
                        },
                        new
                        {
                            Id = "ws-4",
                            Code = "PB",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "4",
                            OfficeId = "office-ft-1",
                            PositionX = 1m,
                            PositionY = 2m
                        },
                        new
                        {
                            Id = "ws-5",
                            Code = "F1",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "5",
                            OfficeId = "office-ft-1",
                            PositionX = 2m,
                            PositionY = 2m
                        },
                        new
                        {
                            Id = "ws-6",
                            Code = "Szp",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "6",
                            OfficeId = "office-ft-1",
                            PositionX = 3m,
                            PositionY = 2m
                        },
                        new
                        {
                            Id = "ws-7",
                            Code = "F2",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "7",
                            OfficeId = "office-ft-1",
                            PositionX = 2m,
                            PositionY = 3m
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany("Offices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.HasOne("Entities.Models.AppUser", "User")
                        .WithMany("OfficeBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Workstation", "Workstation")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.HasOne("Entities.Models.Office", "Office")
                        .WithMany("Workstations")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Navigation("OfficeBookings");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
