// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AbsenceManagerDbContext))]
    partial class AbsenceManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Budapest"
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "Name")
                        .IsUnique();

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alapértelmezett iroda",
                            DisplayOrder = 1,
                            IsActive = true,
                            LocationId = 1,
                            Name = "Iroda 1"
                        });
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_AppUser_BookingDate_IsCancelled");

                    b.HasIndex("WorkstationId", "BookingDate", "IsCancelled")
                        .HasDatabaseName("IX_OfficeBookings_Workstation_BookingDate_IsCancelled");

                    b.ToTable("OfficeBookings", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId", "Code")
                        .IsUnique();

                    b.HasIndex("OfficeId", "Name")
                        .IsUnique();

                    b.ToTable("Workstations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WS-001",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "1. hely",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "WS-002",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "2. hely",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "WS-003",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "3. hely",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "WS-004",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "4. hely",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "WS-005",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "5. hely",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "WS-006",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "6. hely",
                            OfficeId = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany("Offices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Entities.Models.OfficeBooking", b =>
                {
                    b.HasOne("Entities.Models.AppUser", "AppUser")
                        .WithMany("OfficeBookings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Workstation", "Workstation")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.HasOne("Entities.Models.Office", "Office")
                        .WithMany("Workstations")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Navigation("OfficeBookings");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("Entities.Models.Office", b =>
                {
                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Entities.Models.Workstation", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
